- name: installing nginx
  hosts: web
  tasks:
  - name: installing the nginx
    ansible.builtin.package:
      name: nginx
      state: installed

- name: run the nginx
  hosts: web
  tasks:
  - name: start the nginx
    ansible.builtin.service:
      name: nginx
      state: started