- name: variables from prompt
  hosts: web
  vars_prompt:
  - name: course
    prompt: please enter the course name
  - name: duration
    prompt: please enter the duration
  - name: trainer_name
    prompt: please enter the trainer name
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "i am learning {{course}} and duration is {{duration}}, trainer name is {{trainer_name}}"
