#if we want to use variables from inventory, please configure .ini file with variables like course="devops"

- name: variables from inventory
  hosts: web
  tasks:

  - name: print the information
    ansible.builtin.debug:
      msg: "i am learingin the {{course}} the duration is {{duration}} and trainer is {{trainer}}"