- name: Printing variable preferrences
  hosts: web
  vars:
    course: "devops"
  vars_prompt:
  - name: course
  vars_files:
  - vars.yaml
  tasks:

  - name: print the variable preferrence
    vars:
      course: "devops"
    ansible.builtin.debug:
      msg: "i am learinig the {{course}}"


# when we are giving variables, the preferrences will be like below

#1. command line/args
#2. Task level
#3. Files
#4. prompt
#5. Play
#6. inventory
#7. Roles