- name: installing packages through loop
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item }}"
      state:  present
    loop:
    - mysql
    - nginx
    - httpd
    - postfix