- name: install and delete packages
  hosts: web
  become: yes
  tasks:
  - name: install and remove packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'mysql', state: 'present' }
    - { name: 'nginx', state: 'absent' }
    - { name: 'postfix', state: 'present' }
    - { name: 'https', state: 'absent' }