- name: command vs shell
  hosts: local
  connection: local
  tasks:
  - name: execute the command
    ansible.builtin.shell: ls -ltr > /tmp/output.txt # login to the server and execute command inside
    # command module, just issues the command

  - name: check the process
    ansible.builtin.shell: ps -ef | grep sshd #shell command login into the system and run as shell
    register: output

  - name: check the process
    ansible.builtin.command: ps -ef | grep sshd #command will not get the shell environment
    register: output
  - name:
    ansible.builtin.debug:
      msg: "{{ output }}"