---
- name: Provision EC2 instances and setup Route 53 records
  hosts: localhost
  gather_facts: false
  vars:
    region: "your-aws-region"
    vpc_id: "your-vpc-id"
    subnet_id: "your-subnet-id"
    security_group_id: "your-security-group-id"
    key_name: "your-ec2-keypair-name"
    instance_type: "t2.micro"
    ami_id: "your-ami-id"
    route53_zone: "your-route53-zone-name"

  tasks:
    - name: Launch EC2 instances
      ec2_instance:
        region: "{{ region }}"
        vpc_subnet_id: "{{ subnet_id }}"
        group_id: "{{ security_group_id }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        key_name: "{{ key_name }}"
        count: 3
        wait: yes
        assign_public_ip: yes
        instance_tags:
          Name: "{{ item }}"
      with_items:
        - frontend
        - backend
        - mysql
      register: ec2_instances

    - name: Add Route 53 records for private IPs
      route53:
        command: create
        zone: "{{ route53_zone }}"
        record: "{{ item.0 }}.internal"
        type: A
        ttl: 300
        value: "{{ item.1.private_ip_address }}"
        aws_access_key: "{{ ansible_env.AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ ansible_env.AWS_SECRET_ACCESS_KEY }}"
      with_together:
        - ["frontend", "backend", "mysql"]
        - "{{ ec2_instances.results }}"

    - name: Add Route 53 record for public IP of frontend
      route53:
        command: create
        zone: "{{ route53_zone }}"
        record: "frontend-public"
        type: A
        ttl: 300
        value: "{{ item.public_ip_address }}"
        aws_access_key: "{{ ansible_env.AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ ansible_env.AWS_SECRET_ACCESS_KEY }}"
      with_items: "{{ ec2_instances.results }}"
      when: item.item == "frontend"
